Support for custom actions in context menu
thoughtspot/ts-chart-sdk pull request #22
Opened 2023-10-25 15:51 UTC by Rohit1508

2023-10-26 09:50 UTC, chetan1507 requested changes

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    contextMenuActionHandler: {},
why is this part of Context Props?

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    contextMenuActionHandler?: ContextMenuActionHandler;
why is this part of context props?

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +        }
This is too specific to OpenContextMenu. 
Please make this generic so that this can be expanded to other operations as needed.
Also we need close context menu operation to clear any existing state too.

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +            processedPayload ?? null,
this is incorrect. please fix the contract above.

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                error?: any;
please avoid any

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +        this.on(
This should be internalOn and not a generic on

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    private contextMenuActionPreProcessor<
This should be specific to the event so that the payload mapping is not general.

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +        (eventPayload?.[0] as any)?.customActions.forEach(
avoid any at all places.

2023-10-26 09:50 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                contextMenuActionHandler[action.id] = action.onClick;
you ll also need to pass the arguments here as we discussed.

2023-10-26 09:50 UTC, chetan1507 commented on src/types/common.types.ts
> +    id: string;
this should also have event and clicked point and selected points as arguments

2023-10-26 09:50 UTC, chetan1507 commented on src/types/ts-to-chart-event.types.ts
> +    customAction: ContextMenuCustomAction;
Shouldnt this be id only?

2023-10-26 09:50 UTC, chetan1507 commented on src/types/common.types.ts
> +    id: string;
move this in the events only and not in common.

2023-10-26 09:50 UTC, chetan1507 commented
Please add and update unit tests also.

2023-10-26 10:40 UTC, Rohit1508 commented on src/types/ts-to-chart-event.types.ts
> +    customAction: ContextMenuCustomAction;
no, here I need to add points details as well

2023-10-26 10:56 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +        }
we are only storing the mapping of action id with its callback, then why we need to clear it on close context menu event. But we can optimise this to avoid calling contextMenuActionPreProcessor when we already have the mappings.

2023-10-31 06:41 UTC, chetan1507 requested changes

2023-10-31 06:41 UTC, chetan1507 commented on src/types/ts-to-chart-event.types.ts
> +    selectedPoints?: Point[];
add event also here.

2023-10-31 06:41 UTC, chetan1507 commented on src/types/ts-to-chart-event.types.ts
> +    columnIds: string[];
add event here too.

2023-10-31 06:41 UTC, chetan1507 commented on src/types/chart-to-ts-event.types.ts
> +    [key: string]: () => void;
will this not be called with a payload?

2023-10-31 06:41 UTC, chetan1507 commented on src/types/chart-to-ts-event.types.ts
> +    [key: string]: () => void;
same as above?

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                return eventPayload?.[0];
we can have multiple elements in payload right? why send just the first one?

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    ): OpenAxisMenuEventPayload {
the input and output should be consistent. We have changed from array to object.

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    ): OpenContextMenuEventPayload {
the input and output should be consistent. We have changed from array to object.

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +            eventPayload?.[0] as any
why is this required to be treated as any?

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +            eventPayload?.[0] as any
why any?

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    ) {
add return type.

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +            } => {
isnt return type defined as void?

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +            ): {
isnt return type defined as void?

2023-10-31 06:41 UTC, chetan1507 commented on src/main/custom-chart-context.spec.ts
> +        test('should process the event payload for context menu when custom actions are not defined', async () => {
We need to also add test for the callback trigger for custom actions once the event is dispatched from app for both context menu and axis menu.

2023-10-31 12:39 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +            } => {
no we are returning the acknowledgement here to TS app either valid or error response

2023-10-31 12:39 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +            ): {
no we are returning the acknowledgement here to TS app either valid or error response

2023-11-02 06:33 UTC, chetan1507 requested changes

2023-11-02 06:33 UTC, chetan1507 commented on src/types/chart-to-ts-event.types.ts
> +    [key: string]: (...args: any[]) => void;
update this

2023-11-02 06:33 UTC, chetan1507 commented on src/types/chart-to-ts-event.types.ts
> +    [key: string]: (...args: any[]) => void;
same as above, update this.

2023-11-02 06:33 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                    return {
add a logger.

2023-11-02 06:33 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                    return {
add a logger.

2023-11-06 06:09 UTC, merged