Dynamic config + visual props POC
thoughtspot/ts-chart-sdk pull request #26
Opened 2024-02-13 13:57 UTC by Rohit1508

2024-02-14 09:38 UTC, chetan1507 requested changes

2024-02-14 09:38 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    chartConfigEditorDefinition?: (
this should be backward compatible. We still need to support constant definition

2024-02-14 09:38 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +        chartModel: ChartModel,
can we put all of this in the chart state like object?

2024-02-14 09:38 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    ) => VisualPropEditorDefinition;
same as above.

2024-02-14 09:38 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                                );
this can also change the configEditorDefinition

2024-02-14 09:38 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                            ...validationResponse,
this is accurate, same should be there above.

2024-02-14 09:38 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                    this.chartContextProps.chartConfigEditorDefinition(this.chartModel, defaultChartConfig),
should be backward compatible.

2024-02-15 06:53 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +                    this.chartContextProps.chartConfigEditorDefinition(this.chartModel, defaultChartConfig),
Based on callback type( if it is a function or simple object) we can define its execution

2024-02-15 06:53 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +    chartConfigEditorDefinition?: (
Based on callback type( if it is a function or simple object) we can define its execution

2024-02-16 11:41 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +        chartModel: ChartModel,
done

2024-02-16 11:41 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +    ) => VisualPropEditorDefinition;
done

2024-02-16 11:41 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +                                );
done

2024-02-16 11:41 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +                            ...validationResponse,
done

2024-02-16 11:59 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +                    this.chartContextProps.chartConfigEditorDefinition(this.chartModel, defaultChartConfig),
done

2024-02-16 11:59 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +    chartConfigEditorDefinition?: (
done

2024-02-22 05:03 UTC, chetan1507 requested changes

2024-02-22 05:03 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                        )
please extract this into a common private function and reuse at all places.

2024-02-22 05:03 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                        )
please do necessary null checks also. We don't want to update the definition unnecessarily.

2024-02-22 05:03 UTC, chetan1507 commented on src/types/common.types.ts
> +    chartConfigEditorDefinition?: ChartConfigEditorDefinition[];
why are these optional?

2024-02-23 14:32 UTC, Rohit1508 commented on src/types/common.types.ts
> +    chartConfigEditorDefinition?: ChartConfigEditorDefinition[];
There are case where we are only returning {isValid} where validation callbacks are not defined in custom charts

2024-02-27 05:17 UTC, chetan1507 requested changes

2024-02-27 05:17 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +} from '../types/configurator.types';
I think there is dependency cycle issue due to the imports that we have.
Please resolve this.

Also would be good to add dependency cycle lint in the current codebase.

2024-02-27 05:17 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    public getChartConfigEditorDefinition = ({
This cannot be public function.

2024-02-27 05:17 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +    public getVisualPropEditorDefinition = ({
same as above.

2024-02-27 05:17 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                                this.chartModel.config?.chartConfig,
This should be empty as this has not changed.

2024-02-27 05:17 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +                            updatedVisualProps: this.chartModel?.visualProps,
this should be empty.

2024-02-27 05:17 UTC, chetan1507 commented on src/main/custom-chart-context.ts
> +            const defaultState = {
we should only send this when these are updated.

2024-02-27 05:17 UTC, chetan1507 commented on src/types/common.types.ts
> +    chartConfigEditorDefinition?: ChartConfigEditorDefinition[];
lets separate these 2 flows then. 
Lets not reuse objects and have a more concrete contract which doesnt have optional params.

2024-02-27 05:30 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +                                this.chartModel.config?.chartConfig,
But for getting latest definition we need to pass both visual props as well as chart config

2024-02-27 05:33 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +                            updatedVisualProps: this.chartModel?.visualProps,
for getting latest definition we need to pass both visual props as well as chart config.
User can extract `visualProps` here from ctx but if we pass it explicitly it would be more convenient for dev.

2024-02-27 12:31 UTC, Rohit1508 commented on src/main/custom-chart-context.ts
> +                                this.chartModel.config?.chartConfig,
Its  good to pass both chartConfig as well as visual props for fetching the definition because either it is visual update or config update, we are trigerring the setter for both config definition and visual definition. It would be unnecessary confusion for user while defining the definition function that which one to prefer(visual props from arg or from ctx).
Will change the naming convention here for better understanding

2024-03-28 12:33 UTC, closed without merging