Dynamic AllowedConfiguration
thoughtspot/ts-chart-sdk pull request #30
Opened 2024-04-03 18:18 UTC by yashvardhan-n

2024-04-04 07:00 UTC, chetan1507 requested changes
unit tests.

2024-04-04 07:00 UTC, chetan1507 commented on src/types/ts-to-chart-event.types.ts
> +    // Whether user wants thoughtspot default number and conditional formatting
lets add a more generic message here. 
Toggle native configurations supported by TS UI. Ex: column level number and conditional formatting.

Also add versioning details like below.
/**
     * visual properties editor definition
     *
     * @version SDK: 0.1 | ThoughtSpot:
     */

2024-06-11 12:50 UTC, yashvardhan-n commented on src/main/custom-chart-context.ts
> +        allowNumberFormatting: false,
ack

2024-06-11 12:50 UTC, yashvardhan-n commented on src/types/ts-to-chart-event.types.ts
> +    // Whether user wants thoughtspot default number and conditional formatting
ack

2024-06-12 06:19 UTC, Rohit1508 approved these changes

2024-06-12 08:46 UTC, merged