React SDK
thoughtspot/ts-chart-sdk pull request #8
Opened 2023-07-25 06:09 UTC by divyamlamiyan

2023-07-25 06:26 UTC, chetan1507 requested changes

2023-07-25 06:26 UTC, chetan1507 commented on example/react/custom-bar-chart/App.css
Remove empty files

2023-07-25 06:26 UTC, chetan1507 commented on example/react/custom-bar-chart/assets/react.svg
remove

2023-07-25 06:26 UTC, chetan1507 commented on example/react/custom-bar-chart/package.json
> +  "name": "vite-project",
update name.

2023-07-25 06:26 UTC, chetan1507 commented on example/react/custom-bar-chart/public/vite.svg
remove

2023-07-25 06:26 UTC, chetan1507 commented on pnpm-lock.yaml
lets update package locks too.

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +}
Move all types and interface to a types.ts file inside react.

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +        // TODO: do a better mapping for ChartToTSEvent and PayloadMap
whats pending here? can we close this?

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +const emitter = (ctx: CustomChartContext) => {
return type is not defined.
Please add detailed jsdoc comments to each part of the code.

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +export type TSToChartEventListener = {
Please add detailed jsdoc comments to each part of the code.

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +const eventListener = (ctx: CustomChartContext) => {
same as above

Also lets move emitter and eventListeners to different files each.

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +const ChartContext = createContext<ChartContextProps>({} as ChartContextProps);
ReactChartContext ?

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +interface ChartContextProps
ReactChartContextProps

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +    children: any;
this cannot be any

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +                console.log(e);
can we add more meaningful error message?
Also is this an error? lets do console error if thats the case.
Should we not throw the error here?

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +    const initializeProvider = async (ctx2: CustomChartContext) => {
please add comments for all the state variables and every function

2023-07-25 06:26 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +        <ChartContext.Provider value={getChartContextValues(ctx as any)}>
should not have any.

2023-07-25 06:50 UTC, chetan1507 requested changes

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
can we rename file to chart context provider?

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +                args: ChartToTSEventsPayloadMap[typeof eventName],
there can be multiple args here right? That doesn't seem to have been taken care of.

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +        // TODO: do a better mapping for ChartToTSEvent and PayloadMap
can we resolve this?

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +                callbackFn: TSToChartEventsPayloadMap[typeof eventName],
this doesnt look like a callback function and looks more like object map. is this accurate?

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +    const chartRef = useRef(null);
remove

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +    const initializeProvider = async (ctx2: CustomChartContext) => {
better name than ctx2?

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +                chartRef.current = children;
why do we need this?

2023-07-25 06:50 UTC, chetan1507 commented on src/react/custom-chart.context.tsx
> +                chartRef.current = children;
how do we trigger render chart from backend and then it updates the same?

2023-07-28 07:09 UTC, chetan1507 requested changes

2023-07-28 07:09 UTC, chetan1507 commented on src/react/custom-chart-context-hook.tsx
> +        [chartModel, key, hasInitialized],
ctx also.

2023-07-28 07:09 UTC, chetan1507 commented on src/react/custom-chart-context-hook.tsx
> +    props: CustomChartContextProps,
remove renderChart from here.

2023-07-28 07:09 UTC, chetan1507 commented on example/react/custom-bar-chart/App.tsx
> +    renderChart: (cx) => {
remove this from renderChart from the render.

2023-07-28 07:09 UTC, chetan1507 commented on example/react/custom-bar-chart/line-chart.component.tsx
move this inside the src folder.

2023-07-28 07:09 UTC, chetan1507 commented on example/react/custom-bar-chart/line-chart.component.tsx
add comments as much as possible to help developers understand the example better.

2023-07-28 07:09 UTC, chetan1507 commented on example/react/custom-bar-chart/line-chart.component.tsx
> +    // useEffect(() => {
have we tested this?

2023-07-28 07:09 UTC, chetan1507 commented on example/react/custom-bar-chart/line-chart.component.tsx
> +    emitRenderStart([]);
only if intialized

2023-07-30 18:04 UTC, divyamlamiyan commented on example/react/custom-bar-chart/line-chart.component.tsx
Done

2023-08-09 19:57 UTC, ashubham commented on example/react/custom-bar-chart/src/App.tsx
> +        WrapperComponent,
TSChartContext

2023-08-09 19:57 UTC, ashubham commented on example/react/custom-bar-chart/src/App.tsx
> +        onVisualPropsUpdate,
setOnVisualPropsUpdate

2023-08-09 19:57 UTC, ashubham commented on example/react/custom-bar-chart/src/App.tsx
> +        offVisualPropsUpdate,
setOffVisualPropsUpdate

2023-08-09 19:57 UTC, ashubham commented on example/react/custom-bar-chart/src/line-chart.component.tsx
> +            emitRenderComplete();
`emitRenderComplete` should be called after the rendering of the chart is complete

2023-08-21 04:44 UTC, chetan1507 requested changes

2023-08-21 04:44 UTC, chetan1507 commented on example/react/custom-bar-chart/src/App.css
Remove this file

2023-08-21 04:44 UTC, chetan1507 commented on example/react/custom-bar-chart/src/line-chart.component.tsx
> +            emitRenderStart();
https://www.chartjs.org/docs/3.9.1/api/interfaces/Plugin.html#afterrender
Lets add a todo to leverage this.

2023-08-21 04:44 UTC, chetan1507 commented on src/react/use-custom-chart-context.spec.tsx
> +    // test.only('TSChartContext renders children should increase counter for
can we fix this?

2023-08-21 04:44 UTC, chetan1507 commented on src/react/use-custom-chart-context.tsx
> +const evenOfftListener = (
spelling?

2023-08-21 04:44 UTC, chetan1507 commented on src/react/use-custom-chart-context.tsx
> +const emitter = (ctx: CustomChartContext): ChartToTSEventEmitters => {
move to utils

2023-08-21 04:44 UTC, chetan1507 commented on src/react/use-custom-chart-context.tsx
> +const eventListener = (ctx: CustomChartContext): TSToChartEventListener => {
move to utils

2023-08-21 04:44 UTC, chetan1507 commented on src/react/use-custom-chart-context.tsx
> +const evenOfftListener = (
move to utils

2023-08-21 04:44 UTC, chetan1507 commented on src/react/use-custom-chart-context.tsx
> +        setupEventListeners(context);
we ll also need to call off function here too right? to destroy the chart?

2023-08-23 05:08 UTC, merged